# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2bbabe80ec5e74edb734182db6254a82eaa49d6e9681c5577a69119cfeed5d463d364f8b14e39d76b51424741e36836e8c628dd0163a2a26b71e0547771e321

test:
  secret_key_base: 319650fa96895d3e416dcc86fd0ce3d3364865f65782c3f1831a72870996aa1d230b785d63bb4cc234a9e5a19cdf344cb61d0a845d1de181b3cf9d0801502843

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
